import type { Project, Task } from './types'

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Website redesign',
    status: 'Active',
    taskCount: 24,
    createdAt: new Date('2026-03-01'),
  },
  {
    id: '2',
    name: 'Mobile app v2',
    status: 'Active',
    taskCount: 18,
    createdAt: new Date('2026-02-15'),
  },
  {
    id: '3',
    name: 'API refactor',
    status: 'Planning',
    taskCount: 5,
    createdAt: new Date('2026-04-01'),
  },
  {
    id: '4',
    name: 'Q1 marketing site',
    status: 'Archived',
    taskCount: 31,
    createdAt: new Date('2025-12-10'),
  },
  {
    id: '5',
    name: 'Internal docs portal',
    status: 'Active',
    taskCount: 12,
    createdAt: new Date('2026-03-22'),
  },
  {
    id: '6',
    name: 'Onboarding flow redesign',
    status: 'Planning',
    taskCount: 7,
    createdAt: new Date('2026-04-10'),
  },
]

export const mockTasks: Task[] = [
  {
    id: 't1',
    projectId: '1',
    title: 'Set up design system',
    description: 'Define tokens and base components',
    status: 'Done',
    priority: 'High',
    createdAt: new Date('2026-03-02'),
  },
  {
    id: 't2',
    projectId: '1',
    title: 'Rebuild hero section',
    description: null,
    status: 'InProgress',
    priority: 'High',
    createdAt: new Date('2026-03-05'),
  },
  {
    id: 't3',
    projectId: '1',
    title: 'Migrate pricing page',
    description: 'Include comparison table',
    status: 'Todo',
    priority: 'Medium',
    createdAt: new Date('2026-03-10'),
  },
  {
    id: 't4',
    projectId: '2',
    title: 'Implement push notifications',
    description: null,
    status: 'InProgress',
    priority: 'High',
    createdAt: new Date('2026-02-20'),
  },
  {
    id: 't5',
    projectId: '2',
    title: 'Add offline mode',
    description: 'Cache last viewed tasks',
    status: 'Todo',
    priority: 'Medium',
    createdAt: new Date('2026-03-01'),
  },
  {
    id: 't6',
    projectId: '3',
    title: 'Document API v2 endpoints',
    description: null,
    status: 'Todo',
    priority: 'Low',
    createdAt: new Date('2026-04-02'),
  },
  {
    id: 't7',
    projectId: '3',
    title: 'Benchmark current API',
    description: 'p50 / p95 / p99',
    status: 'InProgress',
    priority: 'Medium',
    createdAt: new Date('2026-04-05'),
  },
]
